import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {RegistrationProvider} from "@/context/RegistrationContext";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
        <body className={"light bg-background"}>
        <main className={"light text-foreground bg-background"}>
            <RegistrationProvider>
                {children}
            </RegistrationProvider>
        </main>
        </body>
        </html>
    );
}
